// ROTA DE ESTUDIOS
POST http://localhost:3333/gameStudios
Content-Type: application/json

{
  "studioName": "FromSoftware"
}

### 
GET http://localhost:3333/gameStudios/cc43685f-6fdf-4173-bdd1-7e8cdb3bfc36



// ROTA DE USUARIOS
### 
POST http://localhost:3333/users
Content-Type: application/json

{
  "email": "teste@gmail.com",
  "password": "123456"
}

###
GET http://localhost:3333/users/81412d6f-1601-4672-8a70-644b813df72e


### 
GET http://localhost:3333/users


###
POST http://localhost:3333/users/81412d6f-1601-4672-8a70-644b813df72e/userGames/c5236637-a0fc-4cc9-9546-49ebe4314bae
Content-Type: application/json

{

  "status": 1
}

###
DELETE http://localhost:3333/users/81412d6f-1601-4672-8a70-644b813df72e/userGames/c5236637-a0fc-4cc9-9546-49ebe4314bae


###
PATCH http://localhost:3333/users/81412d6f-1601-4672-8a70-644b813df72e/userGames/c5236637-a0fc-4cc9-9546-49ebe4314bae
Content-Type: application/json

{
  "status": 2
}

###
GET http://localhost:3333/users/81412d6f-1601-4672-8a70-644b813df72e/userGames


###
PATCH http://localhost:3333/users/81412d6f-1601-4672-8a70-644b813df72e
Content-Type: application/json

{
  "userName": "MathQuente",
  "profilePicture": "https://res-console.cloudinary.com/dtdkzusmw/thumbnails/v1/image/upload/v1711491010/aW1hZ2VzL3huY2w0aGM3M2t1cXltaXlvemNv/grid_landscape"
}

### 
DELETE http://localhost:3333/users/c8c0e419-3807-4e0d-9358-2e69190d97ed
// ROTA DE GAMES

###
GET http://localhost:3333/games/c5236637-a0fc-4cc9-9546-49ebe4314bae

###
GET http://localhost:3333/games

###
POST http://localhost:3333/games/cc43685f-6fdf-4173-bdd1-7e8cdb3bfc36
Content-Type: application/json

{
  "gameName": "Dark Souls 3",
  "gameBanner": "https://static-cdn.jtvnw.net/ttv-boxart/490292_IGDB-285x380.jpg",
  "gameDateRelease" : "2022-02-25T03:00:00.000Z",
  "categories": [
    {
      "categoryName": "RPG"
    },
    {
      "categoryName" : "Action RPG"
    }
  ]
}
